name: 'coverage'
on:
    push:
        branches:
            - main
jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - uses: jwalton/gh-find-current-pr@v1
            - uses: actions/checkout@v2
            - run: npm install
            - uses: ArtiomTr/jest-coverage-report-action@v2